### ISSUE TITLE
testing website obama bin liden

### ISSUE THREAD

**Issue by icaaaaaaaaaaaa** [korban-mantan/korban-mantan.github.io#4]
1. bagian page about me, bahasa belum diubah ke bahasa asli.
2. bagian page contact me, belum di ituin ya wkwk 
![Screenshot_2024-02-26-11-34-43-89_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/korban-mantan/korban-mantan.github.io/assets/161274273/48275eb0-8f9b-40cd-981c-a3ae7770e286)

**Comment by Annurofiq** [comment]
Sebaiknya anda selesaikan sendiri aja!!

**Comment by icaaaaaaaaaaaa** [comment]
apaloo

**Comment by korban-mantan** [comment]
ywdah aja si
